apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spark-driver
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    component: spark-driver
spec:
  clusterIP: None
  selector:
    spark-role: driver
    release: {{ .Release.Name }}
    component: spark-driver
  ports:
  - name: spark-ui
    protocol: TCP
    port: 4040
    targetPort: 4040